"""
Django settings for cw project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

SITE_ID = 1

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=sfn@p71dkxy42uc316z$f&@xjy1v1pnu_(mm0#0cpq@ld133v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'base.apps.BaseConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.flatpages',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'clearcache',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static'
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'


# TinyMCE
TINYMCE_DEFAULT_CONFIG = {
    'plugins': 'paste,link',
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 10,
    'browser_spellcheck': True,
    'promotion': False,
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# AWS S3 Upload Configuration
# Helper function to extract AWS credentials from boto3's default credential chain
# This works for both local dev (AWS CLI credentials) and Lambda (IAM role)
def _get_aws_credentials():
    """Extract AWS credentials from boto3's default credential chain."""
    import os
    try:
        import boto3
        session = boto3.Session()
        credentials = session.get_credentials()
        if credentials:
            # Extract credentials from boto3 (works for both AWS CLI and IAM roles)
            access_key = credentials.access_key
            secret_key = credentials.secret_key
            # Session token is required for temporary credentials (IAM roles in Lambda)
            session_token = getattr(credentials, 'token', None) or os.environ.get('AWS_SESSION_TOKEN', '')
            return access_key, secret_key, session_token
    except Exception:
        pass
    # Fallback to environment variables
    return (
        os.environ.get('AWS_ACCESS_KEY_ID', ''),
        os.environ.get('AWS_SECRET_ACCESS_KEY', ''),
        os.environ.get('AWS_SESSION_TOKEN', '')
    )

# Extract credentials (will be overridden by environment-specific settings if needed)
_aws_creds = _get_aws_credentials()
AWS_ACCESS_KEY_ID = _aws_creds[0]
AWS_SECRET_ACCESS_KEY = _aws_creds[1]
AWS_SESSION_TOKEN = _aws_creds[2]

AWS_STORAGE_BUCKET_NAME = ''
S3UPLOAD_REGION = 'us-east-1'

# S3 Upload Destinations
S3UPLOAD_DESTINATIONS = {
    'text_pdf': {
        'key': 'texts',
        'allowed_types': ['application/pdf'],
        'allowed_extensions': ['.pdf'],
        'acl': 'public-read',
    }
}
