# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 02:45
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20161029_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
