# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161029_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
