# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_text_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkimage',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='talks',
        ),
        migrations.AlterField(
            model_name='text',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='texts'),
        ),
        migrations.DeleteModel(
            name='TalkImage',
        ),
    ]
