# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161101_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='_talk_talks_+', to='base.Talk'),
        ),
        migrations.AddField(
            model_name='talkimage',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Talk'),
        ),
    ]
