# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-20 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20161101_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ['name'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='talkimage',
            options={'verbose_name': 'Media Image', 'verbose_name_plural': 'Media Images'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='text',
            name='category',
            field=models.CharField(choices=[('tx', 'Text'), ('teaching', 'Teaching')], default='tx', max_length=20),
        ),
    ]
