# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-02-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20180111_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='system',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
