# Generated by Django 4.1.3 on 2022-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190203_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='talk_talks', to='base.talk'),
        ),
    ]
