# Generated by Django 6.0.1 on 2026-01-11 15:59

from django.db import migrations

import base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_talk_talks'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='text',
                    name='pdf',
                    field=base.models.S3UploadFieldWithPath(blank=True, dest='text_pdf', null=True),
                ),
            ],
        ),
    ]
