# Generated by Django 6.0.1 on 2026-01-11 15:59

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_talk_talks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='pdf',
            field=base.models.S3UploadFieldWithPath(blank=True, dest='text_pdf', null=True),
        ),
    ]
