# Generated by Django 5.2.11 on 2026-09-12 19:06

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_talk_talks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=base.models.S3UploadFieldWithPath(dest='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=base.models.S3UploadFieldWithPath(dest='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='systemimage',
            name='image',
            field=base.models.S3UploadFieldWithPath(dest='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='talkimage',
            name='image',
            field=base.models.S3UploadFieldWithPath(dest='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='text',
            name='pdf',
            field=base.models.S3UploadFieldWithPath(blank=True, dest='text_pdf', null=True),
        ),
    ]
