# Generated by Django 5.2.11 on 2026-10-05 23:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_contentblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
